version: '3.8'
services:
  postgres:
    image: quay.io/fedora/postgresql-16:latest
    environment:
      POSTGRESQL_USER: guestbook
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_DATABASE: guestbook
    ports:
      - "5432:5432"

  redis:
    image: quay.io/kurs/redis:latest
    environment:
      REDIS_PASSWORD: yourpassword
    ports:
      - "6379:6379"

  backend:
    image: guestbook-backend
    build:
      context: ./backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: guestbook
      DB_PASSWORD: password
      DB_NAME: guestbook
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: yourpassword
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  frontend:
    image: guestbook-frontend
    build:
      context: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
