name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_BACKEND: guestbook-api
  IMAGE_FRONTEND: guestbook-web

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

   
    - name: Set IMAGE_TAG
      run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

   
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.25

    
    - name: Verify Go modules
      run: |
        cd backend
        go mod verify

    
    - name: Test backend
      run: |
        cd backend
        make test || go test ./...

    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    
    - name: Build backend image
      run: |
        docker build -t guestbook-api:${IMAGE_TAG} ./backend

   
    - name: Build frontend image
      run: |
        docker build -t guestbook-web:${IMAGE_TAG} ./frontend

    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "24"

    - name: Install HTMLHint
      run: npm install -g htmlhint

    - name: Run frontend lint
      working-directory: ./frontend
      run: make lint

    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    
    - name: Push backend image
      run: |
        docker tag guestbook-api:${IMAGE_TAG} ${{ env.REGISTRY }}/svetlanaglad/guestbook-api:${IMAGE_TAG}
        docker push ${{ env.REGISTRY }}/svetlanaglad/guestbook-api:${IMAGE_TAG}

    - name: Push frontend image
      run: |
        docker tag guestbook-web:${IMAGE_TAG} ${{ env.REGISTRY }}/svetlanaglad/guestbook-web:${IMAGE_TAG}
        docker push ${{ env.REGISTRY }}/svetlanaglad/guestbook-web:${IMAGE_TAG}

